--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Sep 22 2015 13:39
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Select Database: 'db_name'
--
USE db_name
GO
 
IF DB_NAME() = 'db_name'
    RAISERROR('''db_name'' DATABASE CONTEXT NOW IN USE.',1,1)
ELSE
    RAISERROR('ERROR IN BATCH FILE, ''USE db_name'' FAILED!  KILLING THE SPID NOW.',22,127) WITH LOG
 
GO

--
-- Create Table    : 'Person'   
-- Fornavn         :  
-- Mellemnavn      :  
-- Efternavn       :  
-- Forhold         :  
-- PersonID        :  
--
CREATE TABLE Person (
    Fornavn        CHAR(200) NOT NULL,
    Mellemnavn     CHAR(200) NULL,
    Efternavn      CHAR(200) NOT NULL,
    Forhold        CHAR(200) NOT NULL,
    PersonID       INT NOT NULL,
CONSTRAINT pk_Person PRIMARY KEY CLUSTERED (PersonID))
GO

--
-- Create Table    : 'Telefonummer'   
-- Nummer          :  
-- Type            :  
-- NummerID        :  
--
CREATE TABLE Telefonummer (
    Nummer         INT NOT NULL,
    Type           CHAR(200) NOT NULL,
    NummerID       INT NOT NULL,
CONSTRAINT pk_Telefonummer PRIMARY KEY CLUSTERED (NummerID))
GO

--
-- Create Table    : 'Adresse'   
-- Vejnavn         :  
-- Husnummer       :  
-- Postnummer      :  
-- Bynavn          :  
-- Type            :  
-- AdresseID       :  
--
CREATE TABLE Adresse (
    Vejnavn        CHAR(200) NOT NULL,
    Husnummer      INT NOT NULL,
    Postnummer     INT NOT NULL,
    Bynavn         CHAR(200) NOT NULL,
    Type           CHAR(200) NOT NULL,
    AdresseID      INT NOT NULL,
CONSTRAINT pk_Adresse PRIMARY KEY CLUSTERED (AdresseID))
GO

--
-- Create Table    : 'PersonTelefonnumer'   
-- PersonID        :  (references Person.PersonID)
-- NummerID        :  (references Telefonummer.NummerID)
--
CREATE TABLE PersonTelefonnumer (
    PersonID       INT NOT NULL,
    NummerID       INT NOT NULL,
CONSTRAINT pk_PersonTelefonnumer PRIMARY KEY CLUSTERED (PersonID,NummerID),
CONSTRAINT fk_PersonTelefonnumer FOREIGN KEY (PersonID)
    REFERENCES Person (PersonID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
CONSTRAINT fk_PersonTelefonnumer2 FOREIGN KEY (NummerID)
    REFERENCES Telefonummer (NummerID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'PersonAdresse'   
-- PersonID        :  (references Person.PersonID)
-- AdresseID       :  (references Adresse.AdresseID)
--
CREATE TABLE PersonAdresse (
    PersonID       INT NOT NULL,
    AdresseID      INT NOT NULL,
CONSTRAINT pk_PersonAdresse PRIMARY KEY CLUSTERED (PersonID,AdresseID),
CONSTRAINT fk_PersonAdresse FOREIGN KEY (PersonID)
    REFERENCES Person (PersonID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
CONSTRAINT fk_PersonAdresse2 FOREIGN KEY (AdresseID)
    REFERENCES Adresse (AdresseID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

