--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Sep 21 2015 08:44
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Select Database: 'db_name'
--

CREATE DATABASE db_name
GO

USE db_name
GO
 
IF DB_NAME() = 'db_name'
    RAISERROR('''db_name'' DATABASE CONTEXT NOW IN USE.',1,1)
ELSE
    RAISERROR('ERROR IN BATCH FILE, ''USE db_name'' FAILED!  KILLING THE SPID NOW.',22,127) WITH LOG
 
GO
-- EXECUTE SP_DBOPTION 'db_name' ,'TRUNC. LOG ON CHKPT.' ,'TRUE'
-- GO

--
-- Create Table    : 'Person'   
-- Fornavn         :  
-- Mellemnavn      :  
-- Efternavn       :  
-- Forhold         :  
-- PersonID        :  
--
CREATE TABLE Person (
    Fornavn        CHAR(200) NOT NULL,
    Mellemnavn     CHAR(200) NULL,
    Efternavn      CHAR(200) NOT NULL,
    Forhold        CHAR(200) NOT NULL,
    PersonID       INT IDENTITY(1,1) NOT NULL,
	CONSTRAINT pk_Person PRIMARY KEY  (PersonID))
GO

--
-- Create Table    : 'Telefonummer'   
-- Nummer          :  
-- Type            :  
-- NummerID        :  
--
CREATE TABLE Telefonnummer (
    Nummer         INT NOT NULL,
    Type           char(200) NOT NULL,
    NummerID       INT IDENTITY(1,1) NOT NULL,
	CONSTRAINT pk_Nummer PRIMARY KEY  (NummerID))
GO

--
-- Create Table    : 'Adresse'   
-- Vejnavn         :  
-- Husnummer       :  
-- Postnummer      :  
-- Bynavn          :  
-- Type            :  
-- AdresseID       :  
--
CREATE TABLE Adresse (
    Vejnavn        CHAR(200) NOT NULL,
    Husnummer      INT NOT NULL,
    Postnummer     INT NOT NULL,
    Bynavn         CHAR(200) NOT NULL,
    Type           CHAR(200) NOT NULL,
    AdresseID      INT IDENTITY(1,1) NOT NULL,
	CONSTRAINT pk_Adresse PRIMARY KEY  (AdresseID))
GO

--
-- Create Table    : 'PersonAdresse'   
-- PersonID        :  (references Person.PersonID)
-- NummerID        :  (references Telefonummer.NummerID)
--
CREATE TABLE PersonAdresse (
    PersonID       INT NOT NULL,
    AdresseID       INT NOT NULL,
CONSTRAINT pk_PersonAdresse PRIMARY KEY CLUSTERED (PersonID,AdresseID),
CONSTRAINT fk_PersonAdresse FOREIGN KEY (PersonID)
    REFERENCES Person (PersonID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
CONSTRAINT fk_PersonAdresse2 FOREIGN KEY (AdresseID)
    REFERENCES Adresse (AdresseID)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'PersonTelefonnumre'   
-- PersonID        :  (references Person.PersonID)
-- AdresseID       :  (references Adresse.AdresseID)
--
CREATE TABLE PersonTelefonnumre (
    PersonID       INT NOT NULL,
    NummerID      INT NOT NULL,
CONSTRAINT pk_PersonTelefonnumre PRIMARY KEY CLUSTERED (PersonID,NummerID),
CONSTRAINT fk_PersonTelefonnumre FOREIGN KEY (PersonID)
    REFERENCES Person (PersonID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
CONSTRAINT fk_PersonTelefonnumre2 FOREIGN KEY (NummerID)
    REFERENCES Telefonnummer (NummerID)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
GO


